from .domain_prompts import (
    DOMAIN_SYSTEM_PROMPTS,
    get_system_prompt,
    QUERY_CLASSIFIER_PROMPT,
    SQL_GENERATOR_PROMPT,
    WEB_SYNTHESIZER_PROMPT,
    COMBINED_SYNTHESIZER_PROMPT,
)

__all__ = [
    "DOMAIN_SYSTEM_PROMPTS",
    "get_system_prompt",
    "QUERY_CLASSIFIER_PROMPT",
    "SQL_GENERATOR_PROMPT",
    "WEB_SYNTHESIZER_PROMPT",
    "COMBINED_SYNTHESIZER_PROMPT",
]
